version: '3.8'

services:
  dev:
    container_name: dono-gifts-parser
    stdin_open: true
    build:
      context: .
    depends_on:
      - postgres_db
    ports:
      - 3000:3000
    command: npm run serve
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-accounts/donoDevServiceAccountKey.json
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/dono_db
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src:/app/src
  postgres_db:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dono_db
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
