name: Deploy to dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy source code to Cloud Run
    runs-on: ubuntu-latest
    environment: dev
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER_ID }}
          service_account: 'github-actions-account@ninecoins.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'server-app'
          source: './'
          region: 'europe-west1'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'

